# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Users\teore\scoop\apps\cmake\3.31.6\bin\cmake.exe

# The command to remove a file.
RM = C:\Users\teore\scoop\apps\cmake\3.31.6\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\teore\Documents\open_gl-graphics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\teore\Documents\open_gl-graphics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\Users\teore\scoop\apps\cmake\3.31.6\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\Users\teore\scoop\apps\cmake\3.31.6\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\teore\Documents\open_gl-graphics\CMakeFiles C:\Users\teore\Documents\open_gl-graphics\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\teore\Documents\open_gl-graphics\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hephaestus-openGL

# Build rule for target.
hephaestus-openGL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 hephaestus-openGL
.PHONY : hephaestus-openGL

# fast build rule for target.
hephaestus-openGL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/build
.PHONY : hephaestus-openGL/fast

include/imgui/backends/imgui_impl_glfw.obj: include/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_glfw.obj

# target to build an object file
include/imgui/backends/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_glfw.cpp.obj

include/imgui/backends/imgui_impl_glfw.i: include/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/backends/imgui_impl_glfw.cpp.i

include/imgui/backends/imgui_impl_glfw.s: include/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/backends/imgui_impl_glfw.cpp.s

include/imgui/backends/imgui_impl_opengl3.obj: include/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_opengl3.obj

# target to build an object file
include/imgui/backends/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.obj

include/imgui/backends/imgui_impl_opengl3.i: include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.i

include/imgui/backends/imgui_impl_opengl3.s: include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.s

include/imgui/imgui.obj: include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.obj

# target to build an object file
include/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.cpp.obj

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_draw.obj: include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.obj

# target to build an object file
include/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.cpp.obj

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_tables.obj: include/imgui/imgui_tables.cpp.obj
.PHONY : include/imgui/imgui_tables.obj

# target to build an object file
include/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_tables.cpp.obj
.PHONY : include/imgui/imgui_tables.cpp.obj

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.obj: include/imgui/imgui_widgets.cpp.obj
.PHONY : include/imgui/imgui_widgets.obj

# target to build an object file
include/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_widgets.cpp.obj
.PHONY : include/imgui/imgui_widgets.cpp.obj

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/glad.obj: src/glad.c.obj
.PHONY : src/glad.obj

# target to build an object file
src/glad.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/glad.c.obj
.PHONY : src/glad.c.obj

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/input.obj: src/input.cpp.obj
.PHONY : src/input.obj

# target to build an object file
src/input.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/input.cpp.obj
.PHONY : src/input.cpp.obj

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/object.obj: src/object.cpp.obj
.PHONY : src/object.obj

# target to build an object file
src/object.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/object.cpp.obj
.PHONY : src/object.cpp.obj

src/object.i: src/object.cpp.i
.PHONY : src/object.i

# target to preprocess a source file
src/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/object.cpp.i
.PHONY : src/object.cpp.i

src/object.s: src/object.cpp.s
.PHONY : src/object.s

# target to generate assembly for a file
src/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/object.cpp.s
.PHONY : src/object.cpp.s

src/stb_image.obj: src/stb_image.cpp.obj
.PHONY : src/stb_image.obj

# target to build an object file
src/stb_image.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/stb_image.cpp.obj
.PHONY : src/stb_image.cpp.obj

src/stb_image.i: src/stb_image.cpp.i
.PHONY : src/stb_image.i

# target to preprocess a source file
src/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/stb_image.cpp.i
.PHONY : src/stb_image.cpp.i

src/stb_image.s: src/stb_image.cpp.s
.PHONY : src/stb_image.s

# target to generate assembly for a file
src/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hephaestus-openGL.dir\build.make CMakeFiles/hephaestus-openGL.dir/src/stb_image.cpp.s
.PHONY : src/stb_image.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... hephaestus-openGL
	@echo ... include/imgui/backends/imgui_impl_glfw.obj
	@echo ... include/imgui/backends/imgui_impl_glfw.i
	@echo ... include/imgui/backends/imgui_impl_glfw.s
	@echo ... include/imgui/backends/imgui_impl_opengl3.obj
	@echo ... include/imgui/backends/imgui_impl_opengl3.i
	@echo ... include/imgui/backends/imgui_impl_opengl3.s
	@echo ... include/imgui/imgui.obj
	@echo ... include/imgui/imgui.i
	@echo ... include/imgui/imgui.s
	@echo ... include/imgui/imgui_draw.obj
	@echo ... include/imgui/imgui_draw.i
	@echo ... include/imgui/imgui_draw.s
	@echo ... include/imgui/imgui_tables.obj
	@echo ... include/imgui/imgui_tables.i
	@echo ... include/imgui/imgui_tables.s
	@echo ... include/imgui/imgui_widgets.obj
	@echo ... include/imgui/imgui_widgets.i
	@echo ... include/imgui/imgui_widgets.s
	@echo ... src/glad.obj
	@echo ... src/glad.i
	@echo ... src/glad.s
	@echo ... src/input.obj
	@echo ... src/input.i
	@echo ... src/input.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/object.obj
	@echo ... src/object.i
	@echo ... src/object.s
	@echo ... src/stb_image.obj
	@echo ... src/stb_image.i
	@echo ... src/stb_image.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

