# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/monolith/Desktop/openGL_learning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/monolith/Desktop/openGL_learning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/monolith/Desktop/openGL_learning/CMakeFiles /home/monolith/Desktop/openGL_learning//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/monolith/Desktop/openGL_learning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hephaestus-openGL

# Build rule for target.
hephaestus-openGL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hephaestus-openGL
.PHONY : hephaestus-openGL

# fast build rule for target.
hephaestus-openGL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/build
.PHONY : hephaestus-openGL/fast

include/ImGuizmo/GraphEditor.o: include/ImGuizmo/GraphEditor.cpp.o
.PHONY : include/ImGuizmo/GraphEditor.o

# target to build an object file
include/ImGuizmo/GraphEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/GraphEditor.cpp.o
.PHONY : include/ImGuizmo/GraphEditor.cpp.o

include/ImGuizmo/GraphEditor.i: include/ImGuizmo/GraphEditor.cpp.i
.PHONY : include/ImGuizmo/GraphEditor.i

# target to preprocess a source file
include/ImGuizmo/GraphEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/GraphEditor.cpp.i
.PHONY : include/ImGuizmo/GraphEditor.cpp.i

include/ImGuizmo/GraphEditor.s: include/ImGuizmo/GraphEditor.cpp.s
.PHONY : include/ImGuizmo/GraphEditor.s

# target to generate assembly for a file
include/ImGuizmo/GraphEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/GraphEditor.cpp.s
.PHONY : include/ImGuizmo/GraphEditor.cpp.s

include/ImGuizmo/ImCurveEdit.o: include/ImGuizmo/ImCurveEdit.cpp.o
.PHONY : include/ImGuizmo/ImCurveEdit.o

# target to build an object file
include/ImGuizmo/ImCurveEdit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImCurveEdit.cpp.o
.PHONY : include/ImGuizmo/ImCurveEdit.cpp.o

include/ImGuizmo/ImCurveEdit.i: include/ImGuizmo/ImCurveEdit.cpp.i
.PHONY : include/ImGuizmo/ImCurveEdit.i

# target to preprocess a source file
include/ImGuizmo/ImCurveEdit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImCurveEdit.cpp.i
.PHONY : include/ImGuizmo/ImCurveEdit.cpp.i

include/ImGuizmo/ImCurveEdit.s: include/ImGuizmo/ImCurveEdit.cpp.s
.PHONY : include/ImGuizmo/ImCurveEdit.s

# target to generate assembly for a file
include/ImGuizmo/ImCurveEdit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImCurveEdit.cpp.s
.PHONY : include/ImGuizmo/ImCurveEdit.cpp.s

include/ImGuizmo/ImGradient.o: include/ImGuizmo/ImGradient.cpp.o
.PHONY : include/ImGuizmo/ImGradient.o

# target to build an object file
include/ImGuizmo/ImGradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImGradient.cpp.o
.PHONY : include/ImGuizmo/ImGradient.cpp.o

include/ImGuizmo/ImGradient.i: include/ImGuizmo/ImGradient.cpp.i
.PHONY : include/ImGuizmo/ImGradient.i

# target to preprocess a source file
include/ImGuizmo/ImGradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImGradient.cpp.i
.PHONY : include/ImGuizmo/ImGradient.cpp.i

include/ImGuizmo/ImGradient.s: include/ImGuizmo/ImGradient.cpp.s
.PHONY : include/ImGuizmo/ImGradient.s

# target to generate assembly for a file
include/ImGuizmo/ImGradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImGradient.cpp.s
.PHONY : include/ImGuizmo/ImGradient.cpp.s

include/ImGuizmo/ImGuizmo.o: include/ImGuizmo/ImGuizmo.cpp.o
.PHONY : include/ImGuizmo/ImGuizmo.o

# target to build an object file
include/ImGuizmo/ImGuizmo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImGuizmo.cpp.o
.PHONY : include/ImGuizmo/ImGuizmo.cpp.o

include/ImGuizmo/ImGuizmo.i: include/ImGuizmo/ImGuizmo.cpp.i
.PHONY : include/ImGuizmo/ImGuizmo.i

# target to preprocess a source file
include/ImGuizmo/ImGuizmo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImGuizmo.cpp.i
.PHONY : include/ImGuizmo/ImGuizmo.cpp.i

include/ImGuizmo/ImGuizmo.s: include/ImGuizmo/ImGuizmo.cpp.s
.PHONY : include/ImGuizmo/ImGuizmo.s

# target to generate assembly for a file
include/ImGuizmo/ImGuizmo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImGuizmo.cpp.s
.PHONY : include/ImGuizmo/ImGuizmo.cpp.s

include/ImGuizmo/ImSequencer.o: include/ImGuizmo/ImSequencer.cpp.o
.PHONY : include/ImGuizmo/ImSequencer.o

# target to build an object file
include/ImGuizmo/ImSequencer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImSequencer.cpp.o
.PHONY : include/ImGuizmo/ImSequencer.cpp.o

include/ImGuizmo/ImSequencer.i: include/ImGuizmo/ImSequencer.cpp.i
.PHONY : include/ImGuizmo/ImSequencer.i

# target to preprocess a source file
include/ImGuizmo/ImSequencer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImSequencer.cpp.i
.PHONY : include/ImGuizmo/ImSequencer.cpp.i

include/ImGuizmo/ImSequencer.s: include/ImGuizmo/ImSequencer.cpp.s
.PHONY : include/ImGuizmo/ImSequencer.s

# target to generate assembly for a file
include/ImGuizmo/ImSequencer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/ImGuizmo/ImSequencer.cpp.s
.PHONY : include/ImGuizmo/ImSequencer.cpp.s

include/imgui/backends/imgui_impl_glfw.o: include/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/backends/imgui_impl_glfw.o

# target to build an object file
include/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/backends/imgui_impl_glfw.cpp.o

include/imgui/backends/imgui_impl_glfw.i: include/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/backends/imgui_impl_glfw.cpp.i

include/imgui/backends/imgui_impl_glfw.s: include/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/backends/imgui_impl_glfw.cpp.s

include/imgui/backends/imgui_impl_opengl3.o: include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
include/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.o

include/imgui/backends/imgui_impl_opengl3.i: include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.i

include/imgui/backends/imgui_impl_opengl3.s: include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.s

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/audio_manager.o: src/audio_manager.cpp.o
.PHONY : src/audio_manager.o

# target to build an object file
src/audio_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/audio_manager.cpp.o
.PHONY : src/audio_manager.cpp.o

src/audio_manager.i: src/audio_manager.cpp.i
.PHONY : src/audio_manager.i

# target to preprocess a source file
src/audio_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/audio_manager.cpp.i
.PHONY : src/audio_manager.cpp.i

src/audio_manager.s: src/audio_manager.cpp.s
.PHONY : src/audio_manager.s

# target to generate assembly for a file
src/audio_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/audio_manager.cpp.s
.PHONY : src/audio_manager.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/game_object.o: src/game_object.cpp.o
.PHONY : src/game_object.o

# target to build an object file
src/game_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/game_object.cpp.o
.PHONY : src/game_object.cpp.o

src/game_object.i: src/game_object.cpp.i
.PHONY : src/game_object.i

# target to preprocess a source file
src/game_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/game_object.cpp.i
.PHONY : src/game_object.cpp.i

src/game_object.s: src/game_object.cpp.s
.PHONY : src/game_object.s

# target to generate assembly for a file
src/game_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/game_object.cpp.s
.PHONY : src/game_object.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/input.o: src/input.cpp.o
.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model.o: src/model.cpp.o
.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/raycast.o: src/raycast.cpp.o
.PHONY : src/raycast.o

# target to build an object file
src/raycast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/raycast.cpp.o
.PHONY : src/raycast.cpp.o

src/raycast.i: src/raycast.cpp.i
.PHONY : src/raycast.i

# target to preprocess a source file
src/raycast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/raycast.cpp.i
.PHONY : src/raycast.cpp.i

src/raycast.s: src/raycast.cpp.s
.PHONY : src/raycast.s

# target to generate assembly for a file
src/raycast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/raycast.cpp.s
.PHONY : src/raycast.cpp.s

src/render_manager.o: src/render_manager.cpp.o
.PHONY : src/render_manager.o

# target to build an object file
src/render_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/render_manager.cpp.o
.PHONY : src/render_manager.cpp.o

src/render_manager.i: src/render_manager.cpp.i
.PHONY : src/render_manager.i

# target to preprocess a source file
src/render_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/render_manager.cpp.i
.PHONY : src/render_manager.cpp.i

src/render_manager.s: src/render_manager.cpp.s
.PHONY : src/render_manager.s

# target to generate assembly for a file
src/render_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/render_manager.cpp.s
.PHONY : src/render_manager.cpp.s

src/scene.o: src/scene.cpp.o
.PHONY : src/scene.o

# target to build an object file
src/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/scene.cpp.o
.PHONY : src/scene.cpp.o

src/scene.i: src/scene.cpp.i
.PHONY : src/scene.i

# target to preprocess a source file
src/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/scene.cpp.i
.PHONY : src/scene.cpp.i

src/scene.s: src/scene.cpp.s
.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/scene.cpp.s
.PHONY : src/scene.cpp.s

src/sphere_collision.o: src/sphere_collision.cpp.o
.PHONY : src/sphere_collision.o

# target to build an object file
src/sphere_collision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/sphere_collision.cpp.o
.PHONY : src/sphere_collision.cpp.o

src/sphere_collision.i: src/sphere_collision.cpp.i
.PHONY : src/sphere_collision.i

# target to preprocess a source file
src/sphere_collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/sphere_collision.cpp.i
.PHONY : src/sphere_collision.cpp.i

src/sphere_collision.s: src/sphere_collision.cpp.s
.PHONY : src/sphere_collision.s

# target to generate assembly for a file
src/sphere_collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/sphere_collision.cpp.s
.PHONY : src/sphere_collision.cpp.s

src/stb_image.o: src/stb_image.cpp.o
.PHONY : src/stb_image.o

# target to build an object file
src/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/stb_image.cpp.o
.PHONY : src/stb_image.cpp.o

src/stb_image.i: src/stb_image.cpp.i
.PHONY : src/stb_image.i

# target to preprocess a source file
src/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/stb_image.cpp.i
.PHONY : src/stb_image.cpp.i

src/stb_image.s: src/stb_image.cpp.s
.PHONY : src/stb_image.s

# target to generate assembly for a file
src/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/stb_image.cpp.s
.PHONY : src/stb_image.cpp.s

src/texture.o: src/texture.cpp.o
.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i
.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s
.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/texture_debugger.o: src/texture_debugger.cpp.o
.PHONY : src/texture_debugger.o

# target to build an object file
src/texture_debugger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/texture_debugger.cpp.o
.PHONY : src/texture_debugger.cpp.o

src/texture_debugger.i: src/texture_debugger.cpp.i
.PHONY : src/texture_debugger.i

# target to preprocess a source file
src/texture_debugger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/texture_debugger.cpp.i
.PHONY : src/texture_debugger.cpp.i

src/texture_debugger.s: src/texture_debugger.cpp.s
.PHONY : src/texture_debugger.s

# target to generate assembly for a file
src/texture_debugger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/texture_debugger.cpp.s
.PHONY : src/texture_debugger.cpp.s

src/ui.o: src/ui.cpp.o
.PHONY : src/ui.o

# target to build an object file
src/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/ui.cpp.o
.PHONY : src/ui.cpp.o

src/ui.i: src/ui.cpp.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

tracy/public/TracyClient.o: tracy/public/TracyClient.cpp.o
.PHONY : tracy/public/TracyClient.o

# target to build an object file
tracy/public/TracyClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/tracy/public/TracyClient.cpp.o
.PHONY : tracy/public/TracyClient.cpp.o

tracy/public/TracyClient.i: tracy/public/TracyClient.cpp.i
.PHONY : tracy/public/TracyClient.i

# target to preprocess a source file
tracy/public/TracyClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/tracy/public/TracyClient.cpp.i
.PHONY : tracy/public/TracyClient.cpp.i

tracy/public/TracyClient.s: tracy/public/TracyClient.cpp.s
.PHONY : tracy/public/TracyClient.s

# target to generate assembly for a file
tracy/public/TracyClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hephaestus-openGL.dir/build.make CMakeFiles/hephaestus-openGL.dir/tracy/public/TracyClient.cpp.s
.PHONY : tracy/public/TracyClient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hephaestus-openGL"
	@echo "... include/ImGuizmo/GraphEditor.o"
	@echo "... include/ImGuizmo/GraphEditor.i"
	@echo "... include/ImGuizmo/GraphEditor.s"
	@echo "... include/ImGuizmo/ImCurveEdit.o"
	@echo "... include/ImGuizmo/ImCurveEdit.i"
	@echo "... include/ImGuizmo/ImCurveEdit.s"
	@echo "... include/ImGuizmo/ImGradient.o"
	@echo "... include/ImGuizmo/ImGradient.i"
	@echo "... include/ImGuizmo/ImGradient.s"
	@echo "... include/ImGuizmo/ImGuizmo.o"
	@echo "... include/ImGuizmo/ImGuizmo.i"
	@echo "... include/ImGuizmo/ImGuizmo.s"
	@echo "... include/ImGuizmo/ImSequencer.o"
	@echo "... include/ImGuizmo/ImSequencer.i"
	@echo "... include/ImGuizmo/ImSequencer.s"
	@echo "... include/imgui/backends/imgui_impl_glfw.o"
	@echo "... include/imgui/backends/imgui_impl_glfw.i"
	@echo "... include/imgui/backends/imgui_impl_glfw.s"
	@echo "... include/imgui/backends/imgui_impl_opengl3.o"
	@echo "... include/imgui/backends/imgui_impl_opengl3.i"
	@echo "... include/imgui/backends/imgui_impl_opengl3.s"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... src/audio_manager.o"
	@echo "... src/audio_manager.i"
	@echo "... src/audio_manager.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/game_object.o"
	@echo "... src/game_object.i"
	@echo "... src/game_object.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/raycast.o"
	@echo "... src/raycast.i"
	@echo "... src/raycast.s"
	@echo "... src/render_manager.o"
	@echo "... src/render_manager.i"
	@echo "... src/render_manager.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/sphere_collision.o"
	@echo "... src/sphere_collision.i"
	@echo "... src/sphere_collision.s"
	@echo "... src/stb_image.o"
	@echo "... src/stb_image.i"
	@echo "... src/stb_image.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/texture_debugger.o"
	@echo "... src/texture_debugger.i"
	@echo "... src/texture_debugger.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... tracy/public/TracyClient.o"
	@echo "... tracy/public/TracyClient.i"
	@echo "... tracy/public/TracyClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

